# database/Dockerfile

# Use official PostgreSQL image as base
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=testuser
ENV POSTGRES_PASSWORD=testpassword
ENV POSTGRES_DB=testdatabase

# Expose the port PostgreSQL runs on
EXPOSE 5432
